version: '2'
services:
  module-a:
    build:
      context: ./module-a
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
  module-b:
    build:
      context: ./module-a
      dockerfile: ./Dockerfile
    ports:
      - 8082:8082
  portal:
    build:
      context: ./module-a
      dockerfile: ./Dockerfile
    depends_on:
      - module-a
      - module-b
    ports:
      - 8080:8080
